/**
 * 课程元数据：首页与示例页共用同一套「概念 → 案例」说明
 * id 与 URL 路径中的文件夹名一致
 */
export const LESSONS = [
  {
    id: '01-hello-cube',
    href: '/examples/01-hello-cube/',
    stage: 'basics',
    index: '01',
    title: 'Hello Cube',
    summary: '第一次把 3D 画到网页上',
    concepts: [
      'Scene：装下所有物体的舞台',
      'Camera：从哪里看、看得有多宽（fov / aspect）',
      'Renderer：把场景画到 <canvas> 上',
      'Mesh = Geometry（形状）+ Material（外观）',
      '动画循环：每帧改旋转再 render',
    ],
    why: '三件套不通，后面灯光、模型、游戏都无从谈起。先追求「能看见、能动」。',
    try: ['把方块换成球体', '改颜色与转速', '再加一个反向旋转的物体'],
    prev: null,
    next: '02-lights-materials',
  },
  {
    id: '02-lights-materials',
    href: '/examples/02-lights-materials/',
    stage: 'basics',
    index: '02',
    title: '灯光与材质',
    summary: '为什么换了 Standard 会变黑',
    concepts: [
      'MeshBasicMaterial 不受光；MeshStandardMaterial 必须有灯',
      'AmbientLight 做底光，DirectionalLight 做主光',
      'metalness / roughness 控制「金属感」与「粗糙度」',
      '阴影：renderer、灯光、物体、地面四处都要开',
    ],
    why: '真实感来自光与材质的配合。很多「全黑场景」其实只是忘了加灯。',
    try: ['关掉环境光只留平行光', '把 roughness 调到 0 和 1 对比', '试 SpotLight'],
    prev: '01-hello-cube',
    next: '03-orbit-controls',
  },
  {
    id: '03-orbit-controls',
    href: '/examples/03-orbit-controls/',
    stage: 'basics',
    index: '03',
    title: '轨道控制器',
    summary: '用鼠标环绕观察场景',
    concepts: [
      'OrbitControls 来自 three/addons，不是核心包',
      'enableDamping 时每帧必须 controls.update()',
      'Group：旋转父节点 = 子物体一起转',
      'Fog / GridHelper：帮助感知空间',
    ],
    why: '产品展示、调试模型都依赖「拖着看」。交互是 3D 网页的第二基本功。',
    try: ['打开 autoRotate', '限制 minDistance / maxDistance', '换成 AxesHelper'],
    prev: '02-lights-materials',
    next: '04-model-loader',
  },
  {
    id: '04-model-loader',
    href: '/examples/04-model-loader/',
    stage: 'basics',
    index: '04',
    title: '模型加载流程',
    summary: '加载后居中与缩放',
    concepts: [
      '真实项目用 GLTFLoader 加载 .glb',
      'Box3 算包围盒 → 居中 → setScalar 统一大小',
      '不同软件单位不同，不处理会巨或看不见',
      'traverse 给子 Mesh 开阴影',
    ],
    why: '业务里几乎都是「加载别人的模型」。后处理三步是刚需套路。',
    try: ['打印包围盒 size', '接入一个真实 GLB', '给手臂加更多动画'],
    prev: '03-orbit-controls',
    next: '05-particles',
  },
  {
    id: '05-particles',
    href: '/examples/05-particles/',
    stage: 'basics',
    index: '05',
    title: '粒子系统',
    summary: '一次画出成千上万个点',
    concepts: [
      '不要为每个点建 Mesh，用 BufferGeometry 批处理',
      'Float32Array 存 position / color',
      'Points + PointsMaterial',
      '改数组后要 needsUpdate = true',
    ],
    why: '星空、雪花、频谱可视化都靠粒子。这是性能友好的「大量物体」入门。',
    try: ['数量改到 20000 看帧率', '每帧扰动 Y', '改成地面萤火虫分布'],
    prev: '04-model-loader',
    next: 'p1-showcase',
  },
  {
    id: 'p1-showcase',
    href: '/examples/p1-showcase/',
    stage: 'practice',
    index: 'P1',
    title: '可交互旋转展台',
    summary: '第一个完整小项目',
    concepts: ['组合灯光 + 阴影 + OrbitControls', 'Group 组装展台与展品', 'HTML 按钮改 material.color'],
    why: '把基础课拼成可演示作品。验收：拖拽流畅、有阴影、可换色。',
    try: ['加金属度滑条', '换成自己的 GLB', '用 Raycaster 点展品出说明'],
    prev: '05-particles',
    next: 'p2-solar-system',
  },
  {
    id: 'p2-solar-system',
    href: '/examples/p2-solar-system/',
    stage: 'practice',
    index: 'P2',
    title: '太阳系（简化版）',
    summary: '父子变换的经典课',
    concepts: ['pivot 旋转 = 公转', '子网格自转', 'Raycaster 点选行星', '多层父子（月球绕地球）'],
    why: '理解坐标系层级后，机械臂、太阳系、挂点动画都通了。',
    try: ['加一颗木星', '给轨道加倾角', '点击后相机飞向行星'],
    prev: 'p1-showcase',
    next: 'p3-dice',
  },
  {
    id: 'p3-dice',
    href: '/examples/p3-dice/',
    stage: 'practice',
    index: 'P3',
    title: '3D 骰子',
    summary: '旋转插值与朝上映射',
    concepts: ['Canvas 纹理画点数', '目标角度表 faceUp', '缓动 easeOut', '多圈空翻 + 落地收敛'],
    why: '游戏感来自「过程」而不只是结果。插值与缓动是动画基本功。',
    try: ['改时长与圈数', 'easeOutBack 回弹', '同时掷两颗'],
    prev: 'p2-solar-system',
    next: 'p4-product',
  },
  {
    id: 'p4-product',
    href: '/examples/p4-product/',
    stage: 'practice',
    index: 'P4',
    title: '产品展示页',
    summary: '换材质与热点标注',
    concepts: ['程序化模型可被 GLB 替换', 'userData 挂卖点文案', 'Raycaster 点部件', '共用 Material 换色'],
    why: '电商 3D 落地页的常见结构：转着看 + 点热点 + 换配色。',
    try: ['加载真实耳机 GLB', '热点改成跟随 HTML 标签', '切换磨砂/亮面'],
    prev: 'p3-dice',
    next: 'p5-gallery',
  },
  {
    id: 'p5-gallery',
    href: '/examples/p5-gallery/',
    stage: 'practice',
    index: 'P5',
    title: '第一人称画廊',
    summary: '走进场景里看',
    concepts: ['PointerLockControls', 'WASD + dt 移动', 'AABB 简易撞墙', '距离判定显示说明'],
    why: '从「在外面看」变成「走进去」。展厅、迷宫、简单 FPS 都从这儿起步。',
    try: ['加中间柱子与碰撞', '空格跳跃', '用地图数组生成墙'],
    prev: 'p4-product',
    next: 'p6-audio-particles',
  },
  {
    id: 'p6-audio-particles',
    href: '/examples/p6-audio-particles/',
    stage: 'practice',
    index: 'P6',
    title: '音频粒子可视化',
    summary: '声音驱动画面',
    concepts: ['AudioContext + AnalyserNode', 'getByteFrequencyData', '频谱映射到粒子高度', '用户手势后才能播音频'],
    why: '连接 Web Audio 与 Three.js。音乐可视化、互动装置常用这套。',
    try: ['接入真 mp3', '改成柱状频谱', '低频控制整体缩放'],
    prev: 'p5-gallery',
    next: 'p7-runner',
  },
  {
    id: 'p7-runner',
    href: '/examples/p7-runner/',
    stage: 'challenge',
    index: 'P7',
    title: '跑酷小游戏',
    summary: '状态机与实例化渲染',
    concepts: ['ready / playing / over', '三车道换道', 'InstancedMesh + frustumCulled', '粗碰撞检测'],
    why: '把渲染、输入、胜负规则收进一个循环。小游戏骨架通用。',
    try: ['加跳跃', '本地最高分', '更多障碍造型'],
    prev: 'p6-audio-particles',
    next: 'p8-dataviz',
  },
  {
    id: 'p8-dataviz',
    href: '/examples/p8-dataviz/',
    stage: 'challenge',
    index: 'P8',
    title: '3D 数据可视化',
    summary: '数字映射成高度',
    concepts: ['value / max → height', '悬停 Tooltip', '切换数据集', 'dispose 防泄漏'],
    why: '可视化的本质是映射。柱状只是最直观的一种通道。',
    try: ['fetch 真实 JSON', '柱子生长动画', '改成圆环排布'],
    prev: 'p7-runner',
    next: 'p9-water-shader',
  },
  {
    id: 'p9-water-shader',
    href: '/examples/p9-water-shader/',
    stage: 'challenge',
    index: 'P9',
    title: 'Shader 水面',
    summary: '自定义 GPU 程序',
    concepts: ['vertex 改顶点位置', 'fragment 算颜色', 'uniforms 传时间', '菲涅尔与高光'],
    why: '当内置材质不够用时，就要自己写着色器。水面是最友好的入门题材。',
    try: ['加大浪振幅', '颜色选择器', '接环境反射进阶'],
    prev: 'p8-dataviz',
    next: 'p10-portfolio-room',
  },
  {
    id: 'p10-portfolio-room',
    href: '/examples/p10-portfolio-room/',
    stage: 'challenge',
    index: 'P10',
    title: '作品集房间',
    summary: '用场景讲故事',
    concepts: ['热点叙事', '场景构图', 'OrbitControls + Raycaster', '可扩展为作品集首页'],
    why: '技术最终要服务表达。把项目做成可点击房间，比列表页更有记忆点。',
    try: ['热点加真实 URL', '换家具 GLB', '点击门切换场景'],
    prev: 'p9-water-shader',
    next: null,
  },
]

export const LESSON_BY_ID = Object.fromEntries(LESSONS.map((l) => [l.id, l]))

export function lessonIdFromPath(pathname = location.pathname) {
  const parts = pathname.split('/').filter(Boolean)
  // /examples/01-hello-cube/ → 01-hello-cube
  const idx = parts.indexOf('examples')
  if (idx >= 0 && parts[idx + 1]) return parts[idx + 1]
  return null
}
